<?php

const SITE_ROOT = __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR;

const PUBLIC_ROOT = SITE_ROOT.'public_html'.DIRECTORY_SEPARATOR;

const IMG_ROOT = PUBLIC_ROOT.'img'.DIRECTORY_SEPARATOR;

